# Generated by Django 5.0.2 on 2024-03-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='admin',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default='Default Room Name', max_length=255),
        ),
    ]
