# Generated by Django 5.0.2 on 2024-03-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameroom_room_url_alter_gameroom_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='admin',
            new_name='game_starter',
        ),
    ]
