# Generated by Django 5.0.2 on 2024-03-13 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameroom_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(default=False, related_name='joined_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
