# Generated by Django 5.0.2 on 2024-03-14 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameroom_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='room_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(related_name='joined_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
