# Generated by Django 5.0.2 on 2024-03-24 23:12

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_phishgamesession_gamestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingAttribute',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('phishing_attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Enter the code for the phishing attribute', max_length=25, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Enter the name for the phishing attribute', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.CharField(help_text='Enter the description for the phishing attribute', max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Phishing Attribute',
                'verbose_name_plural': 'Phishing Attributes',
                'db_table': 'phishing_attribute',
                'default_related_name': 'phishing_attributes',
            },
        ),
        migrations.CreateModel(
            name='PhishGameSessionCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('owner', models.IntegerField(default=0)),
                ('classification', models.IntegerField(default=0)),
                ('selected', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phishgamesession')),
            ],
            options={
                'verbose_name': 'Session Card',
                'verbose_name_plural': 'Session Cards',
                'db_table': 'phishgame_game_session_card',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PhishGameSessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('channel_name', models.CharField(max_length=77)),
                ('connect', models.BooleanField(default=True)),
                ('lifePoints', models.IntegerField(default=100)),
                ('coins', models.IntegerField(default=0)),
                ('ready', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phishgamesession')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Player',
                'verbose_name_plural': 'Session Players',
                'db_table': 'phishgame_game_session_player',
            },
        ),
        migrations.CreateModel(
            name='PhishGameSessionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phishgamesessioncards')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phishingattribute')),
            ],
            options={
                'verbose_name': 'Session Attribute',
                'verbose_name_plural': 'Session Attributes',
                'db_table': 'phishgame_game_session_attribute',
            },
        ),
        migrations.CreateModel(
            name='PhishingSample',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('phishing_sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(editable=False, help_text='Enter a unique identifier for the phishing sample.', max_length=36, unique=True, verbose_name='identifier')),
                ('file_type', models.CharField(choices=[('IMG', 'Image'), ('HTML-IMG', 'HTML with Embedded Image')], default='IMG', help_text='Choose a file type', max_length=10, verbose_name='File Type')),
                ('phishing_sample_file', models.FileField(default='samples/default.html', help_text='Upload a phishing sample', storage=django.core.files.storage.FileSystemStorage(location='/Users/aasthajawa/Desktop/myPhishGameOriginal/phooledgame/media'), upload_to=game.models.sample_upload_path, verbose_name='Phishing Sample File')),
                ('thumbnail', models.ImageField(default='samples/default.png', help_text='Upload a thumbnail for the phishing sample', storage=django.core.files.storage.FileSystemStorage(location='/Users/aasthajawa/Desktop/myPhishGameOriginal/phooledgame/media'), upload_to=game.models.sample_upload_path, verbose_name='Thumbnail')),
                ('sample_type', models.CharField(choices=[('PHISH', 'Phishing'), ('NONPHISH', 'Non-Phishing')], help_text='Enter the sample type', max_length=25, verbose_name='Sample Type')),
                ('explanation', models.CharField(blank=True, default=None, help_text='Explain the attributes/sample type', max_length=500, null=True, verbose_name='Explanation')),
                ('test_sample', models.BooleanField(default=False, help_text='Select if this is a test sample', verbose_name='Test Sample')),
                ('phishing_attributes', models.ManyToManyField(blank=True, to='game.phishingattribute')),
            ],
            options={
                'verbose_name': 'Phishing Sample',
                'verbose_name_plural': 'Phishing Samples',
                'db_table': 'phishing_sample',
                'ordering': ['pk'],
                'default_related_name': 'phishing_sample',
            },
        ),
        migrations.AddField(
            model_name='phishgamesessioncards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phishingsample'),
        ),
    ]
